---
- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Update CentOS Repos
  command: yum -y update

- name: Install dependency $item
  yum: name=$item state=present
  with_items:
    - git
    - subversion
    - mercurial
    - python-pygments
    - libselinux-python

- name: Disable SELinux
  selinux: policy=targeted state=permissive

- name: Permanently disable SELinux
  copy: src=selinux-config dest=/etc/selinux/config

- name: Add alias to 127.0.0.1 to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^127.0.0.1 {{ domain }}"
    line="127.0.0.1 {{ domain }}"
    state=present

- name: Open up some ports
  copy: src=iptables dest=/etc/sysconfig/iptables
  notify: restart iptables
